### ISSUE TITLE
Problemer med "Sociologi ABC" bogen 

### ISSUE THREAD

**Issue by Friggfalksabroe** [lixhq/support#43]
Birgitte Wandall - Mailen: 

Jeg og mine elever oplever desværre stadig følgende problemer med Sociologi ABC:

1: Søgefunktionen i bogen er på engelsk, selvom bogen nu er den korrekte danske version (altså: Når man søger i bogen, kommer citater osv. op på engelsk, og man kan ikke søge på begreberne på dansk (f. eks. får man ingen hits på 'aftraditionalisering' fordi søgefunktionen kun kender til 'detraditionalisation)). Det er virkeligt problematisk, fordi det forhindrer eleverne i at bruge bogen selvstændigt til informationssøgning.

2: Et lidt mindre problem: Sidetallene på selve bogens sider passer ikke med sidetallene i indholdsfortegnelsen og i funktionen 'Jump to'. Hvis man f. eks. indtaster s. 24 i 'Jump to' bliver man sendt til s. 28.

Jeg har været i kontakt med supporten på lix-appen for en uges tid siden, men problemerne er endnu ikke løst (muligvis fordi noget af det havde at gøre med hvordan bogen var indlæst)?

**Comment by ssboisen** [comment]
This issue was moved to lixhq/lix#38
