### ISSUE TITLE
Urgent; Bøgerne hakker, når hun arbejder i dem. 

### ISSUE THREAD

**Issue by Friggfalksabroe** [lixhq/support#63]
andr4891@tietgen.dk

"jeg kan ikke bruge "søgeordsmetoden" uden at den fryser på siderne, og den går uafbrudt offline."

Bøgerne: 

afsætning A - grundbog, 3. udgave, bind 1 

afsætning a - grundbog, 3. opgave, bind 2

**Comment by ssboisen** [comment]
This issue was moved to lixhq/lix#34
