### ISSUE TITLE
Unable to fetch book 

### ISSUE THREAD

**Issue by Friggfalksabroe** [lixhq/support#79]
jotp@eucnord.dk

Han får fejlmeddelelsen: Unable to fetch book at the moment. 
Bog: "Afsætning A: Metode cases og opgaver. 3 udgave, bind 1. 

Han kan heller ikke åbne denne bog, som han ellers har i offline-tilstand: 
Afsætning A - grundbog, 3. udgave bind 2.

**Comment by ssboisen** [comment]
This issue was moved to lixhq/lix#29

**Comment by ssboisen** [comment]
This issue was moved to lixhq/lix#30
